# Generated by Django 5.1.2 on 2025-12-06 15:50

import django.db.models.deletion
import internaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('nro_afiliado', models.CharField(blank=True, max_length=50)),
                ('cobertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internaciones.cobertura')),
            ],
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('diagnostico', models.CharField(blank=True, max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('autorizado', 'Autorizado'), ('pendiente', 'Pendiente'), ('solicitado', 'Solicitado')], default='pendiente', max_length=20)),
                ('prorroga_estado', models.CharField(blank=True, max_length=80)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internaciones', to='internaciones.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('autorizaciones', 'Autorizaciones y Prórrogas'), ('epicrisis', 'Epicrisis'), ('boletin', 'Boletín Operatorio / Parte Anestésico'), ('evol_med', 'Evolución Médica'), ('evol_enf', 'Evolución de Enfermería'), ('interconsultas', 'Interconsultas'), ('laboratorio', 'Laboratorio'), ('imagenes', 'Imágenes'), ('otros', 'Otros documentos')], max_length=30)),
                ('archivo', models.FileField(upload_to=internaciones.models.hc_upload_to)),
                ('nombre_visible', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='internaciones.paciente')),
            ],
        ),
    ]
